# .github/workflows/drift-detection.yml
name: Drift Detection

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.9.0

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
        
        # echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
        if [ $exitcode -eq 2 ]; then
            echo There was a drift!
            exit 1
        else 
            exit 0
        fi

    # - name: Check for Drift
    #    # Check if the previous step failed
    #   run: echo "Drift detected!"

    # - name: Create GitHub Issue if Drift Detected
    #    # Check if the previous step failed
    #   uses: peter-evans/create-issue-from-file@v4
    #   with:
    #     title: "Infrastructure Drift Detected"
    #     content-filepath: .github/drift-issue-template.md
    #     labels: drift, infrastructure
