# name: Terraform GitOps (GCP VM)

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   terraform:
#     name: Terraform Apply
#     runs-on: ubuntu-latest
#     env:
#       GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
#       TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # Setup Terraform
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: 1.9.0

#       # Authenticate to Google Cloud
#       - name: Authenticate to GCP
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       # Initialize Terraform
#       - name: Terraform Init
#         run: terraform init

#       # Format Terraform files
#       - name: Terraform Format
#         run: terraform fmt

#       # Validate Terraform configuration
#       - name: Terraform Validate
#         run: terraform validate

#       # Generate Terraform plan
#       - name: Terraform Plan
#         run: terraform plan -out=tfplan

#       # Apply Terraform changes (only on push to main)
#       - name: Terraform Apply
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         run: terraform apply -auto-approve tfplan

    #   # Clean up
    #   - name: Clean up
    #     if: always()
    #     run: rm -f tfplan
    #     working-directory: ./terraform


name: Terraform Apply and Destroy
on:
  push:
    branches:
      - main

  workflow_dispatch: # Allow manual trigger
jobs:
  terraform-apply:
    if: github.ref != 'refs/heads/destroy' # Skip apply on destroy branch
    runs-on: ubuntu-latest
    env:
      TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x
      - run: terraform init
      - run: terraform apply -auto-approve

  terraform-destroy:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' # Run on destroy branch or manual trigger
    runs-on: ubuntu-latest
    env:
      TF_VAR_google_credentials: ${{ secrets.GCP_SA_KEY }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x
      - run: terraform init
      - run: terraform destroy -auto-approve