name: Terraform

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    terraform:
        name: Terraform
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Terraform
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                    terraform_version: 1.5.0 # Adjust to your required version

            # Initialize Terraform
            - name: Terraform Init
              run: terraform init

            # Format Terraform code
            - name: Terraform Format
              run: terraform fmt

            # Validate Terraform configuration
            - name: Terraform Validate
              run: terraform validate

            # Plan Terraform changes
            - name: Terraform Plan
              run: terraform plan

            # Apply Terraform changes (only on push to main)
            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform apply -auto-approve